version: '3.9'

services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: search_engine_development
            POSTGRES_USER: encora
            POSTGRES_PASSWORD: encora
        ports:
            - 3001:5432
    app:
        build:
            context: .
        ports:
            - 3000:3000
        depends_on:
            - redis
        tty: true
        stdin_open: true
        depends_on:
            - db
        command: "bundle exec rails s -b 0.0.0.0"
